Experiment 'pythonPromptNewToolsExt' is active
> conda info --json
Python interpreter path: /usr/bin/python3
[ERROR 2023-3-6 0:18:14.620]: readdir() failed for "/var/cache/ldconfig" (Error: EACCES: permission denied, scandir '/var/cache/ldconfig')
[ERROR 2023-3-6 0:18:14.653]: readdir() failed for "/var/cache/pollinate" (Error: EACCES: permission denied, scandir '/var/cache/pollinate')
[ERROR 2023-3-6 0:18:14.701]: readdir() failed for "/var/cache/private" (Error: EACCES: permission denied, scandir '/var/cache/private')
[ERROR 2023-3-6 0:18:14.860]: readdir() failed for "/var/lib/amazon" (Error: EACCES: permission denied, scandir '/var/lib/amazon')
[ERROR 2023-3-6 0:18:15.43]: readdir() failed for "/var/lib/polkit-1" (Error: EACCES: permission denied, scandir '/var/lib/polkit-1')
[ERROR 2023-3-6 0:18:15.44]: readdir() failed for "/var/lib/private" (Error: EACCES: permission denied, scandir '/var/lib/private')
[ERROR 2023-3-6 0:18:15.205]: readdir() failed for "/var/lib/udisks2" (Error: EACCES: permission denied, scandir '/var/lib/udisks2')
> /bin/python -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-6 0:18:15.248]: readdir() failed for "/var/log/amazon" (Error: EACCES: permission denied, scandir '/var/log/amazon')
[ERROR 2023-3-6 0:18:15.276]: readdir() failed for "/var/log/private" (Error: EACCES: permission denied, scandir '/var/log/private')
> /bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-6 0:18:15.311]: Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
> /bin/python ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-6 0:18:15.347]: readdir() failed for "/var/spool/rsyslog" (Error: EACCES: permission denied, scandir '/var/spool/rsyslog')
[ERROR 2023-3-6 0:18:15.363]: readdir() failed for "/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-ModemManager.service-lBzsAi" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-ModemManager.service-lBzsAi')
[ERROR 2023-3-6 0:18:15.366]: readdir() failed for "/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-apache2.service-PebBwj" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-apache2.service-PebBwj')
[ERROR 2023-3-6 0:18:15.369]: readdir() failed for "/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-systemd-hostnamed.service-MuoWJh" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-systemd-hostnamed.service-MuoWJh')
[ERROR 2023-3-6 0:18:15.370]: readdir() failed for "/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-systemd-logind.service-uJM3Fg" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-systemd-logind.service-uJM3Fg')
[ERROR 2023-3-6 0:18:15.373]: readdir() failed for "/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-systemd-resolved.service-sKXejj" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-systemd-resolved.service-sKXejj')
[ERROR 2023-3-6 0:18:15.382]: readdir() failed for "/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-systemd-timedated.service-CJjjti" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-systemd-timedated.service-CJjjti')
[ERROR 2023-3-6 0:18:15.389]: readdir() failed for "/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-systemd-timesyncd.service-JaItqh" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-a484ab61982545fca6441f5c86a47e09-systemd-timesyncd.service-JaItqh')
> /usr/bin/python -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-6 0:18:15.459]: Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
> /usr/bin/python ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
> /usr/bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
Starting Pylance language server.
